[versions]
agp = "8.13.0"
kotlin = "2.2.21"
ksp = "2.0.20-1.0.24"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"

# Compose
compose-bom = "2025.10.01"
compose-compiler = "1.6.10"

# AndroidX
core-ktx = "1.17.0"
lifecycle = "2.9.4"
activity-compose = "1.11.0"
navigation = "2.9.5"

# Coroutines
coroutines = "1.10.2"

# AppSearch
appsearch = "1.1.0"

# Markdown / Coil / SAF
markdown-compose = "0.5.0"
coil = "2.7.0"
documentfile = "1.1.0"
datastore = "1.1.7"


[libraries]
# Compose BOM
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }

# Compose UI
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Core / lifeCycle / Activity / Navigation

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }


# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# AppSearch
appsearch-core = { module = "androidx.appsearch:appsearch", version.ref = "appsearch" }
appsearch-local-storage = { module = "androidx.appsearch:appsearch-local-storage", version.ref = "appsearch" }
appsearch-platform-storage = { module = "androidx.appsearch:appsearch-platform-storage", version.ref = "appsearch" }
appsearch-compiler = { module = "androidx.appsearch:appsearch-compiler", version.ref = "appsearch" }

# Markdown Compose
markdown-compose = { module = "com.github.jeziellago:compose-markdown", version.ref = "markdown-compose" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# SAF / DocumentFile
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }


junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }